---
- name: Get vector distrib
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/{{ vector_version }}/vector_{{ vector_version }}-1_amd64.deb"
    dest: "/tmp/vector-{{ vector_version }}.deb"
    mode: '0644'

- name: Update apt cache
  become: true
  ansible.builtin.apt:
    update_cache: true

- name: Install vector
  become: true
  ansible.builtin.command:
    cmd: "dpkg -i /tmp/vector-{{ vector_version }}.deb"
  changed_when: false

- name: Deploy vector configuration
  become: true
  ansible.builtin.template:
    src: templates/vector.yaml.j2
    dest: "{{ vector_config_path }}"
    mode: '0644'
  notify: Start vector service

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
